export const COLUMNS = [
  {
    id: 'immediate',
    label: 'Needs Immediate Attention',
    shortLabel: 'Immediate',
    headerBg: 'bg-[#A6192E]',
    headerText: 'text-white',
    badgeBg: 'bg-[#FCEDEF]',
    badgeText: 'text-[#8B1525]',
    borderColor: 'border-[#E8A0AD]',
    dotColor: 'bg-[#C4233A]',
  },
  {
    id: 'up_next',
    label: 'Up Next',
    shortLabel: 'Up Next',
    headerBg: 'bg-[#B8860B]',
    headerText: 'text-white',
    badgeBg: 'bg-[#FEF6E1]',
    badgeText: 'text-[#8A6508]',
    borderColor: 'border-[#E8CE7D]',
    dotColor: 'bg-[#C9960D]',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    shortLabel: 'In Progress',
    headerBg: 'bg-[#1F3864]',
    headerText: 'text-white',
    badgeBg: 'bg-[#E8EEF6]',
    badgeText: 'text-[#1A2F54]',
    borderColor: 'border-[#9CADC6]',
    dotColor: 'bg-[#2D4E85]',
  },
  {
    id: 'waiting_on',
    label: 'Waiting On',
    shortLabel: 'Waiting On',
    headerBg: 'bg-[#5B3A6E]',
    headerText: 'text-white',
    badgeBg: 'bg-[#F3ECF7]',
    badgeText: 'text-[#4A2D5A]',
    borderColor: 'border-[#C4A8D1]',
    dotColor: 'bg-[#7E4692]',
  },
  {
    id: 'follow_up',
    label: 'Follow Up',
    shortLabel: 'Follow Up',
    headerBg: 'bg-[#2A7A5F]',
    headerText: 'text-white',
    badgeBg: 'bg-[#E8F5F0]',
    badgeText: 'text-[#1F5C4E]',
    borderColor: 'border-[#8EC4B5]',
    dotColor: 'bg-[#3A9480]',
  },
]

export const COLUMN_MAP = Object.fromEntries(COLUMNS.map((c) => [c.id, c]))

export const ALL_STATUSES = [...COLUMNS.map((c) => c.id), 'completed']
