export const COLUMNS = [
  {
    id: 'immediate',
    label: 'Needs Immediate Attention',
    shortLabel: 'Immediate',
    color: 'red',
    headerBg: 'bg-red-600',
    headerText: 'text-white',
    badgeBg: 'bg-red-100',
    badgeText: 'text-red-700',
    borderColor: 'border-red-300',
    dotColor: 'bg-red-500',
  },
  {
    id: 'up_next',
    label: 'Up Next',
    shortLabel: 'Up Next',
    color: 'amber',
    headerBg: 'bg-amber-500',
    headerText: 'text-white',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-700',
    borderColor: 'border-amber-300',
    dotColor: 'bg-amber-400',
  },
  {
    id: 'in_progress',
    label: 'In Progress',
    shortLabel: 'In Progress',
    color: 'blue',
    headerBg: 'bg-blue-600',
    headerText: 'text-white',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-700',
    borderColor: 'border-blue-300',
    dotColor: 'bg-blue-500',
  },
  {
    id: 'waiting_on',
    label: 'Waiting On',
    shortLabel: 'Waiting On',
    color: 'purple',
    headerBg: 'bg-purple-600',
    headerText: 'text-white',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-700',
    borderColor: 'border-purple-300',
    dotColor: 'bg-purple-500',
  },
  {
    id: 'follow_up',
    label: 'Follow Up',
    shortLabel: 'Follow Up',
    color: 'teal',
    headerBg: 'bg-teal-600',
    headerText: 'text-white',
    badgeBg: 'bg-teal-100',
    badgeText: 'text-teal-700',
    borderColor: 'border-teal-300',
    dotColor: 'bg-teal-500',
  },
]

export const COLUMN_MAP = Object.fromEntries(COLUMNS.map((c) => [c.id, c]))

export const ALL_STATUSES = [...COLUMNS.map((c) => c.id), 'completed']
